import type { EvidenceBundle } from "@/lib/evidence/loader";
import {
  byCategory,
  citedSources,
  claimItems,
  companyFieldItems,
  concerns,
  emailItems,
  iso,
  keyFacts,
  meetingItems,
  missingInformation,
  partitionClaims,
  personSummaries,
  suggestedQuestions,
  thesisCompatibility,
  warmIntroductions,
  type PersonSummary,
  type ThesisCompatibility,
  type WarmIntroduction,
} from "@/lib/evidence/sections";
import { safeExternalUrl } from "@/lib/evidence/safe-url";
import type { EvidenceItem, GeneratedItem, KeyFact, SourceRef } from "@/lib/evidence/types";

export const MEETING_BRIEF_VERSION = "meeting-brief-v1";

export type MeetingBriefContent = {
  version: typeof MEETING_BRIEF_VERSION;
  generatedAt: string;
  subject: {
    opportunityId: string;
    companyName: string;
    stage: string;
    meeting: { id: string; title: string | null; startsAt: string; attendees: string[]; href: string | null } | null;
  };
  /** Evidence only: every item carries its class and citations. */
  facts: {
    companyOverview: EvidenceItem[];
    people: PersonSummary[];
    thesis: ThesisCompatibility;
    relationshipHistory: { emails: EvidenceItem[]; pastMeetings: EvidenceItem[]; upcomingMeetings: EvidenceItem[] };
    warmIntroductions: WarmIntroduction[];
    research: EvidenceItem[];
    keyFacts: KeyFact[];
  };
  unverified: EvidenceItem[];
  inferences: EvidenceItem[];
  missingInformation: string[];
  /** Generated by LargeVCModel rules; never presented as fact. */
  generated: { concerns: GeneratedItem[]; questions: GeneratedItem[] };
  sources: SourceRef[];
  counts: { claims: number; sources: number; emails: number; meetings: number; people: number };
};

const OVERVIEW_CATEGORIES = /\b(overview|company|product|description|business)\b/i;

/**
 * Assembles a meeting brief from stored evidence only. Works with partial data: every section has
 * an explicit empty form, and absent facts are listed under missing information.
 */
export function assembleMeetingBrief(bundle: EvidenceBundle): MeetingBriefContent {
  const claims = claimItems(bundle);
  const { established, unverified, inferences } = partitionClaims(claims);
  const facts = keyFacts(claims);
  const companyOverview = [...companyFieldItems(bundle), ...byCategory(established, OVERVIEW_CATEGORIES)];
  const citedItems = [...companyOverview, ...established, ...unverified, ...inferences];
  const pastMeetings = meetingItems(bundle, "past").slice(0, 10);
  const upcomingMeetings = meetingItems(bundle, "upcoming").slice(0, 5);
  const emails = emailItems(bundle).slice(0, 10);
  const sources = citedSources(bundle, citedItems);
  const target = bundle.targetMeeting;

  return {
    version: MEETING_BRIEF_VERSION,
    generatedAt: bundle.now.toISOString(),
    subject: {
      opportunityId: bundle.opportunity.id,
      companyName: bundle.company.name,
      stage: bundle.opportunity.stage,
      meeting: target
        ? { id: target.id, title: target.title, startsAt: target.startsAt.toISOString(), attendees: target.attendees, href: safeExternalUrl(target.htmlLink) }
        : null,
    },
    facts: {
      companyOverview,
      people: personSummaries(bundle),
      thesis: thesisCompatibility(bundle),
      relationshipHistory: { emails, pastMeetings, upcomingMeetings },
      warmIntroductions: warmIntroductions(bundle),
      research: established,
      keyFacts: facts,
    },
    unverified,
    inferences,
    missingInformation: missingInformation(bundle, facts),
    generated: { concerns: concerns(bundle, claims), questions: suggestedQuestions(bundle, facts, claims) },
    sources,
    counts: {
      claims: claims.length,
      sources: sources.length,
      emails: bundle.emails.length,
      meetings: bundle.meetings.length,
      people: bundle.people.length,
    },
  };
}

export function briefTitle(bundle: EvidenceBundle) {
  const meeting = bundle.targetMeeting;
  return meeting ? `${bundle.company.name}: ${meeting.title?.trim() || "meeting"} (${iso(meeting.startsAt)?.slice(0, 10)})` : `${bundle.company.name}: meeting brief`;
}
