export const FIXED_ACCESS_DATE = "2026-07-22T16:00:00.000Z";

export const demoPartners = [
  {
    id: "partner-ava",
    name: "Ava Sterling",
    title: "Managing Partner",
    email: "ava@northstarseed.example",
    location: "San Francisco",
    thesisFocus: "Technical seed fund backing AI infrastructure, developer tooling, and defensible data platforms.",
    avatarInitial: "AS",
  },
  {
    id: "partner-ben",
    name: "Ben Ortiz",
    title: "Partner",
    email: "ben@northstarseed.example",
    location: "Palo Alto",
    thesisFocus: "Open-source infrastructure, security, and technical founders with bottom-up adoption.",
    avatarInitial: "BO",
  },
  {
    id: "partner-rina",
    name: "Rina Kapoor",
    title: "Venture Partner",
    email: "rina@northstarseed.example",
    location: "Menlo Park",
    thesisFocus: "Enterprise AI adoption, workflow automation, and data governance.",
    avatarInitial: "RK",
  },
];

export const demoUsers = [
  {
    id: "user-demo-partner",
    name: "Demo Partner",
    email: "partner@northstarseed.example",
    role: "VC Partner",
  },
];

export const demoThesis = {
  id: "thesis-ai-infra-seed",
  name: "Technical AI Infrastructure Seed Thesis",
  description:
    "Back exceptional technical founders building AI infrastructure primitives where urgency is visible through recent funding, customer pull, developer adoption, or credible warm paths.",
  sectors: "AI Infrastructure,Developer Tools,Data Infrastructure,AI Security,Model Observability",
  stages: "Pre-seed,Seed",
  geographies: "San Francisco,Oakland,Berkeley,Palo Alto,San Mateo,Mountain View,San Jose,Bay Area",
  checkSizeMin: 500000,
  checkSizeMax: 2500000,
};

export const demoCompanies = [
  {
    id: "company-vectorforge",
    slug: "vectorforge-ai",
    name: "VectorForge AI",
    website: "/demo-sources/vectorforge-product",
    description:
      "Demo company building a control plane for vector databases, retrieval quality monitoring, and cost-aware index operations.",
    sector: "AI Infrastructure",
    stage: "Seed",
    headquarters: "San Francisco, CA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$3.2M",
    latestFundingDate: "2026-05-14T00:00:00.000Z",
    checkSizeFit: "$1.5M seed allocation fits target ownership model",
  },
  {
    id: "company-kernelgrid",
    slug: "kernelgrid",
    name: "KernelGrid",
    website: "/demo-sources/kernelgrid-product",
    description:
      "Demo company creating GPU job scheduling, usage forecasting, and cost controls for AI application teams.",
    sector: "AI Infrastructure",
    stage: "Seed",
    headquarters: "Palo Alto, CA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$4.5M",
    latestFundingDate: "2026-02-18T00:00:00.000Z",
    checkSizeFit: "$2.0M lead or co-lead check is plausible",
  },
  {
    id: "company-modelframe",
    slug: "modelframe",
    name: "ModelFrame",
    website: "/demo-sources/modelframe-product",
    description:
      "Demo company building evaluation pipelines and regression monitoring for LLM product teams.",
    sector: "Model Observability",
    stage: "Seed",
    headquarters: "San Francisco, CA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$2.7M",
    latestFundingDate: "2026-06-03T00:00:00.000Z",
    checkSizeFit: "$1.0M participation check fits reserves plan",
  },
  {
    id: "company-guardlayer",
    slug: "guardlayer",
    name: "GuardLayer",
    website: "/demo-sources/guardlayer-product",
    description:
      "Demo company securing AI agents through policy enforcement, runtime inspection, and audit replay.",
    sector: "AI Security",
    stage: "Seed",
    headquarters: "San Mateo, CA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$2.8M",
    latestFundingDate: "2025-12-09T00:00:00.000Z",
    checkSizeFit: "$1.25M seed follow-on capacity is available",
  },
  {
    id: "company-datafoundry",
    slug: "datafoundry-labs",
    name: "DataFoundry Labs",
    website: "/demo-sources/datafoundry-product",
    description:
      "Demo company generating governed synthetic data pipelines for training and evaluating enterprise AI systems.",
    sector: "Data Infrastructure",
    stage: "Seed",
    headquarters: "Berkeley, CA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$3.7M",
    latestFundingDate: "2026-01-29T00:00:00.000Z",
    checkSizeFit: "$1.5M co-lead check is within fund construction",
  },
  {
    id: "company-telemetryfabric",
    slug: "telemetry-fabric",
    name: "Telemetry Fabric",
    website: "/demo-sources/telemetryfabric-product",
    description:
      "Demo company connecting traces, prompts, tool calls, and evaluation results for AI agent operations.",
    sector: "Model Observability",
    stage: "Pre-seed",
    headquarters: "Oakland, CA",
    latestFundingRound: "Pre-seed",
    latestFundingAmount: "$1.1M",
    latestFundingDate: "2026-04-22T00:00:00.000Z",
    checkSizeFit: "$750K seed-extension check could create early ownership",
  },
  {
    id: "company-edgepilot",
    slug: "edgepilot",
    name: "EdgePilot",
    website: "/demo-sources/edgepilot-product",
    description:
      "Demo company deploying compact AI inference runtimes to retail, logistics, and field-service edge devices.",
    sector: "AI Infrastructure",
    stage: "Seed",
    headquarters: "San Jose, CA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$2.4M",
    latestFundingDate: "2025-10-02T00:00:00.000Z",
    checkSizeFit: "$1.0M extension check fits edge-infra allocation",
  },
  {
    id: "company-compileworks",
    slug: "compileworks",
    name: "CompileWorks",
    website: "/demo-sources/compileworks-product",
    description:
      "Demo company building compiler diagnostics and deployment verification for AI-generated production code.",
    sector: "Developer Tools",
    stage: "Seed",
    headquarters: "Mountain View, CA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$2.1M",
    latestFundingDate: "2026-03-11T00:00:00.000Z",
    checkSizeFit: "$1.0M check fits technical seed thesis",
  },
  {
    id: "company-contextharbor",
    slug: "context-harbor",
    name: "Context Harbor",
    website: "/demo-sources/contextharbor-product",
    description:
      "Demo company building enterprise knowledge retrieval governance for regulated customer-support teams.",
    sector: "Enterprise AI",
    stage: "Series A",
    headquarters: "San Francisco, CA",
    latestFundingRound: "Series A",
    latestFundingAmount: "$12M",
    latestFundingDate: "2025-08-20T00:00:00.000Z",
    checkSizeFit: "Later-stage round is outside preferred seed entry",
  },
  {
    id: "company-secureweights",
    slug: "secureweights",
    name: "SecureWeights",
    website: "/demo-sources/secureweights-product",
    description:
      "Demo company building model provenance, checksum policies, and regulated deployment approval workflows.",
    sector: "AI Security",
    stage: "Seed",
    headquarters: "Seattle, WA",
    latestFundingRound: "Seed",
    latestFundingAmount: "$3.0M",
    latestFundingDate: "2026-05-01T00:00:00.000Z",
    checkSizeFit: "$1.25M check fits, geography is outside target filter",
  },
];

export const demoContacts = [
  {
    id: "contact-maya-chen",
    fullName: "Maya Chen",
    email: "maya@vectorforge.demo",
    linkedInUrl: "/demo-sources/maya-chen-profile",
    role: "Co-founder & CEO",
    location: "San Francisco, CA",
    sector: "AI Infrastructure",
    stage: "Seed",
    checkSizeMin: 1000000,
    checkSizeMax: 2000000,
    relationshipStrength: 8,
    researchConfidence: 91,
    crmStatus: "Ranked",
    companyId: "company-vectorforge",
  },
  {
    id: "contact-priya-raman",
    fullName: "Priya Raman",
    email: "priya@kernelgrid.demo",
    linkedInUrl: "/demo-sources/priya-raman-profile",
    role: "Founder & CTO",
    location: "Palo Alto, CA",
    sector: "AI Infrastructure",
    stage: "Seed",
    checkSizeMin: 1500000,
    checkSizeMax: 2500000,
    relationshipStrength: 7,
    researchConfidence: 88,
    crmStatus: "New Lead",
    companyId: "company-kernelgrid",
  },
  {
    id: "contact-samira-haddad",
    fullName: "Samira Haddad",
    email: "samira@modelframe.demo",
    linkedInUrl: "/demo-sources/samira-haddad-profile",
    role: "Co-founder & CEO",
    location: "San Francisco, CA",
    sector: "Model Observability",
    stage: "Seed",
    checkSizeMin: 750000,
    checkSizeMax: 1500000,
    relationshipStrength: 6,
    researchConfidence: 86,
    crmStatus: "Drafted",
    companyId: "company-modelframe",
  },
  {
    id: "contact-devon-brooks",
    fullName: "Devon Brooks",
    email: "devon@guardlayer.demo",
    linkedInUrl: "/demo-sources/devon-brooks-profile",
    role: "Founder",
    location: "San Mateo, CA",
    sector: "AI Security",
    stage: "Seed",
    checkSizeMin: 1000000,
    checkSizeMax: 2000000,
    relationshipStrength: 5,
    researchConfidence: 83,
    crmStatus: "New Lead",
    companyId: "company-guardlayer",
  },
  {
    id: "contact-aisha-okafor",
    fullName: "Aisha Okafor",
    email: "aisha@datafoundry.demo",
    linkedInUrl: "/demo-sources/aisha-okafor-profile",
    role: "Co-founder & CEO",
    location: "Berkeley, CA",
    sector: "Data Infrastructure",
    stage: "Seed",
    checkSizeMin: 1000000,
    checkSizeMax: 2000000,
    relationshipStrength: 6,
    researchConfidence: 84,
    crmStatus: "New Lead",
    companyId: "company-datafoundry",
  },
  {
    id: "contact-luis-alvarez",
    fullName: "Luis Alvarez",
    email: "luis@telemetryfabric.demo",
    linkedInUrl: "/demo-sources/luis-alvarez-profile",
    role: "Co-founder & CTO",
    location: "Oakland, CA",
    sector: "Model Observability",
    stage: "Pre-seed",
    checkSizeMin: 500000,
    checkSizeMax: 1000000,
    relationshipStrength: 9,
    researchConfidence: 80,
    crmStatus: "New Lead",
    companyId: "company-telemetryfabric",
  },
  {
    id: "contact-theo-nguyen",
    fullName: "Theo Nguyen",
    email: "theo@edgepilot.demo",
    linkedInUrl: "/demo-sources/theo-nguyen-profile",
    role: "Founder & CEO",
    location: "San Jose, CA",
    sector: "AI Infrastructure",
    stage: "Seed",
    checkSizeMin: 750000,
    checkSizeMax: 1500000,
    relationshipStrength: 4,
    researchConfidence: 78,
    crmStatus: "New Lead",
    companyId: "company-edgepilot",
  },
  {
    id: "contact-elena-petrova",
    fullName: "Elena Petrova",
    email: "elena@compileworks.demo",
    linkedInUrl: "/demo-sources/elena-petrova-profile",
    role: "Founder",
    location: "Mountain View, CA",
    sector: "Developer Tools",
    stage: "Seed",
    checkSizeMin: 750000,
    checkSizeMax: 1500000,
    relationshipStrength: 6,
    researchConfidence: 82,
    crmStatus: "New Lead",
    companyId: "company-compileworks",
  },
  {
    id: "contact-noah-kim",
    fullName: "Noah Kim",
    email: "noah@contextharbor.demo",
    linkedInUrl: "/demo-sources/noah-kim-profile",
    role: "Co-founder & CEO",
    location: "San Francisco, CA",
    sector: "Enterprise AI",
    stage: "Series A",
    checkSizeMin: 3000000,
    checkSizeMax: 6000000,
    relationshipStrength: 7,
    researchConfidence: 77,
    crmStatus: "Nurture",
    companyId: "company-contextharbor",
  },
  {
    id: "contact-hana-sato",
    fullName: "Hana Sato",
    email: "hana@secureweights.demo",
    linkedInUrl: "/demo-sources/hana-sato-profile",
    role: "Founder & CEO",
    location: "Seattle, WA",
    sector: "AI Security",
    stage: "Seed",
    checkSizeMin: 1000000,
    checkSizeMax: 2000000,
    relationshipStrength: 3,
    researchConfidence: 72,
    crmStatus: "Nurture",
    companyId: "company-secureweights",
  },
  {
    id: "contact-marcus-lee",
    fullName: "Marcus Lee",
    email: "marcus@orbitops.demo",
    linkedInUrl: "/demo-sources/marcus-lee-profile",
    role: "Founder",
    location: "San Francisco, CA",
    sector: "Cloud Cost Management",
    stage: "Pre-seed",
    checkSizeMin: 500000,
    checkSizeMax: 1000000,
    relationshipStrength: 5,
    researchConfidence: 64,
    crmStatus: "New Lead",
    companyId: "company-vectorforge",
  },
  {
    id: "contact-jordan-weiss",
    fullName: "Jordan Weiss",
    email: "jordan@foundryml.demo",
    linkedInUrl: "/demo-sources/jordan-weiss-profile",
    role: "Founder",
    location: "Los Angeles, CA",
    sector: "AI Applications",
    stage: "Pre-seed",
    checkSizeMin: 500000,
    checkSizeMax: 750000,
    relationshipStrength: 2,
    researchConfidence: 58,
    crmStatus: "New Lead",
    companyId: "company-contextharbor",
  },
];

export const demoFounderProfiles = [
  {
    id: "profile-maya-chen",
    contactId: "contact-maya-chen",
    companyId: "company-vectorforge",
    summary:
      "Maya is a repeat infrastructure operator building VectorForge AI, a demo company focused on retrieval infrastructure reliability and cost control.",
    companyDescription:
      "VectorForge AI targets teams running production retrieval systems that need better index observability, drift detection, and capacity management.",
    thesisFit:
      "Strong match for a technical AI infrastructure seed thesis: Bay Area, recent seed, product wedge in retrieval systems, and warm path through a portfolio CTO.",
    concerns:
      "Customer concentration and long-term differentiation versus cloud-native vector database vendors need validation.",
    pastInteractions:
      "Met briefly at the May 2026 AI Systems Summit; partner Ava Sterling added a note to follow up after the seed announcement.",
    outreachHistoryText:
      "No direct outreach sent. One warm intro path identified through portfolio founder Nikhil Shah.",
  },
  {
    id: "profile-priya-raman",
    contactId: "contact-priya-raman",
    companyId: "company-kernelgrid",
    summary:
      "Priya is a systems engineer building GPU scheduling infrastructure for AI teams with volatile training and inference workloads.",
    companyDescription:
      "KernelGrid helps application teams allocate GPU capacity, forecast spend, and route jobs across heterogeneous clusters.",
    thesisFit:
      "High fit due to AI infrastructure focus, recent seed financing, and technical wedge in GPU utilization.",
    concerns:
      "Needs diligence on cloud-provider dependency and whether the product is infrastructure middleware or services-heavy optimization.",
    pastInteractions:
      "Ben Ortiz attended Priya's technical talk at Systems for AI Infra 2026 and flagged the team as credible.",
    outreachHistoryText:
      "No outbound message yet. Possible intro through advisor Lila Fernandez.",
  },
  {
    id: "profile-samira-haddad",
    contactId: "contact-samira-haddad",
    companyId: "company-modelframe",
    summary:
      "Samira is building evaluation and regression testing infrastructure for production LLM applications.",
    companyDescription:
      "ModelFrame gives AI product teams test suites, experiment tracking, and failure clustering before releases.",
    thesisFit:
      "Good thesis fit in model observability with a very recent seed and credible enterprise pain.",
    concerns:
      "Competitive category; need evidence of distribution advantage and durable telemetry network effects.",
    pastInteractions:
      "Rina Kapoor exchanged notes after an enterprise AI governance roundtable.",
    outreachHistoryText:
      "A short draft exists from a prior saved search but was not approved.",
  },
  {
    id: "profile-devon-brooks",
    contactId: "contact-devon-brooks",
    companyId: "company-guardlayer",
    summary:
      "Devon is building runtime security and policy controls for tool-using AI agents.",
    companyDescription:
      "GuardLayer provides permission gates, action replay, and policy templates for AI agents handling sensitive workflows.",
    thesisFit:
      "Relevant to AI security and agent infrastructure, with timing linked to seed fundraising and enterprise pilots.",
    concerns:
      "Need validation that policy enforcement can remain low latency and implementation burden stays manageable.",
    pastInteractions:
      "Shared portfolio connection through Nora Patel, former security lead at a Northstar portfolio company.",
    outreachHistoryText: "No direct outreach yet.",
  },
  {
    id: "profile-aisha-okafor",
    contactId: "contact-aisha-okafor",
    companyId: "company-datafoundry",
    summary:
      "Aisha is building governed synthetic data tooling for enterprise AI evaluation and training loops.",
    companyDescription:
      "DataFoundry Labs creates synthetic datasets with lineage, policy metadata, and evaluation harnesses for regulated buyers.",
    thesisFit:
      "Matches data infrastructure and AI governance interests, with Bay Area location and seed timing.",
    concerns:
      "Need diligence on model-quality claims and procurement velocity in regulated enterprises.",
    pastInteractions:
      "Met at Berkeley AI Builders Night; partner note says the team has strong buyer empathy.",
    outreachHistoryText: "No direct outreach yet.",
  },
  {
    id: "profile-luis-alvarez",
    contactId: "contact-luis-alvarez",
    companyId: "company-telemetryfabric",
    summary:
      "Luis is building observability pipelines for AI agents, joining traces, prompts, tool calls, and evaluation outcomes.",
    companyDescription:
      "Telemetry Fabric focuses on agent reliability teams that need root-cause analysis across tools and model calls.",
    thesisFit:
      "Strong relationship path and clear AI infrastructure relevance, but stage is slightly earlier than the seed filter.",
    concerns:
      "Funding is pre-seed and evidence quality is lighter than the highest-ranked candidates.",
    pastInteractions:
      "Warm second-degree path through portfolio founder Nikhil Shah and shared attendance at AgentOps Demo Day.",
    outreachHistoryText: "No direct outreach yet.",
  },
];

export const internalCrmSource = {
  title: "Internal CRM Snapshot - Demo Data",
  url: "/demo-sources/internal-crm-snapshot",
  publisher: "Northstar Seed Demo CRM",
  publishedAt: "2026-07-01T00:00:00.000Z",
  accessedAt: FIXED_ACCESS_DATE,
  sourceType: "internal_crm",
  origin: "internal_demo",
  snippet:
    "Seeded private CRM record for a fictional demo. Used only to distinguish internal data from public research.",
  supportsClaims: [
    "Founder identity, company association, relationship strength, CRM status, and prior interaction notes are seeded internal demo data.",
  ],
};

export const demoSources = [
  internalCrmSource,
  {
    title: "DEMO SOURCE: VectorForge announces $3.2M seed round",
    url: "/demo-sources/vectorforge-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2026-05-14T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-vectorforge",
    contactId: "contact-maya-chen",
    snippet:
      "VectorForge AI, a fictional demo company, announced a $3.2M seed round to build retrieval infrastructure tooling.",
    supportsClaims: [
      "VectorForge AI is represented in the demo dataset as having raised a $3.2M seed round on May 14, 2026.",
      "Maya Chen is represented as VectorForge AI's co-founder and CEO.",
    ],
  },
  {
    title: "DEMO SOURCE: VectorForge retrieval reliability product brief",
    url: "/demo-sources/vectorforge-product",
    publisher: "VectorForge AI Demo Site",
    publishedAt: "2026-05-21T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "company",
    origin: "mock",
    companyId: "company-vectorforge",
    contactId: "contact-maya-chen",
    snippet:
      "The demo product brief describes vector index monitoring, retrieval drift detection, and cost-aware capacity management.",
    supportsClaims: [
      "VectorForge AI focuses on retrieval infrastructure reliability, drift detection, and index operations.",
      "The product is categorized as AI infrastructure in this demo.",
    ],
  },
  {
    title: "DEMO SOURCE: AI Systems Summit 2026 attendee note",
    url: "/demo-sources/ai-systems-summit-2026",
    publisher: "AI Systems Summit Demo Program",
    publishedAt: "2026-05-09T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "other",
    origin: "mock",
    companyId: "company-vectorforge",
    contactId: "contact-maya-chen",
    snippet:
      "A fictional event record lists Maya Chen and portfolio CTO Nikhil Shah in the same retrieval operations working session.",
    supportsClaims: [
      "Maya Chen and portfolio founder Nikhil Shah attended the same demo retrieval operations session.",
      "The warm introduction path is based on seeded event attendance, not a verified public relationship.",
    ],
  },
  {
    title: "DEMO SOURCE: KernelGrid seed financing brief",
    url: "/demo-sources/kernelgrid-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2026-02-18T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-kernelgrid",
    contactId: "contact-priya-raman",
    snippet:
      "KernelGrid, a fictional demo company, is represented as having raised $4.5M to build GPU orchestration tooling.",
    supportsClaims: [
      "KernelGrid is represented in the demo dataset as having raised a $4.5M seed round on February 18, 2026.",
      "Priya Raman is represented as KernelGrid's founder and CTO.",
    ],
  },
  {
    title: "DEMO SOURCE: KernelGrid GPU scheduler product page",
    url: "/demo-sources/kernelgrid-product",
    publisher: "KernelGrid Demo Site",
    publishedAt: "2026-03-04T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "company",
    origin: "mock",
    companyId: "company-kernelgrid",
    contactId: "contact-priya-raman",
    snippet:
      "The demo product page describes GPU job scheduling, usage forecasting, and routing across clusters.",
    supportsClaims: [
      "KernelGrid focuses on GPU scheduling and cost controls for AI application teams.",
      "The product is categorized as AI infrastructure in this demo.",
    ],
  },
  {
    title: "DEMO SOURCE: ModelFrame seed launch note",
    url: "/demo-sources/modelframe-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2026-06-03T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-modelframe",
    contactId: "contact-samira-haddad",
    snippet:
      "ModelFrame, a fictional demo company, is represented as having raised $2.7M for LLM regression testing.",
    supportsClaims: [
      "ModelFrame is represented in the demo dataset as having raised a $2.7M seed round on June 3, 2026.",
      "Samira Haddad is represented as ModelFrame's co-founder and CEO.",
    ],
  },
  {
    title: "DEMO SOURCE: ModelFrame evaluation pipeline brief",
    url: "/demo-sources/modelframe-product",
    publisher: "ModelFrame Demo Site",
    publishedAt: "2026-06-10T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "company",
    origin: "mock",
    companyId: "company-modelframe",
    contactId: "contact-samira-haddad",
    snippet:
      "The demo brief describes evaluation suites, failure clustering, and release regression monitoring for LLM teams.",
    supportsClaims: [
      "ModelFrame focuses on evaluation pipelines and regression monitoring for LLM product teams.",
      "The product is categorized as model observability in this demo.",
    ],
  },
  {
    title: "DEMO SOURCE: GuardLayer seed funding note",
    url: "/demo-sources/guardlayer-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2025-12-09T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-guardlayer",
    contactId: "contact-devon-brooks",
    snippet:
      "GuardLayer, a fictional demo company, is represented as having raised $2.8M to secure AI agent execution.",
    supportsClaims: [
      "GuardLayer is represented in the demo dataset as having raised a $2.8M seed round on December 9, 2025.",
      "Devon Brooks is represented as GuardLayer's founder.",
    ],
  },
  {
    title: "DEMO SOURCE: GuardLayer agent security product note",
    url: "/demo-sources/guardlayer-product",
    publisher: "GuardLayer Demo Site",
    publishedAt: "2026-01-12T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "company",
    origin: "mock",
    companyId: "company-guardlayer",
    contactId: "contact-devon-brooks",
    snippet:
      "The demo note describes runtime policy enforcement, action replay, and permission gates for AI agents.",
    supportsClaims: [
      "GuardLayer focuses on policy enforcement and runtime inspection for tool-using AI agents.",
      "The product is categorized as AI security in this demo.",
    ],
  },
  {
    title: "DEMO SOURCE: DataFoundry seed announcement",
    url: "/demo-sources/datafoundry-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2026-01-29T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-datafoundry",
    contactId: "contact-aisha-okafor",
    snippet:
      "DataFoundry Labs, a fictional demo company, is represented as having raised $3.7M for governed synthetic data.",
    supportsClaims: [
      "DataFoundry Labs is represented in the demo dataset as having raised a $3.7M seed round on January 29, 2026.",
      "Aisha Okafor is represented as DataFoundry Labs' co-founder and CEO.",
    ],
  },
  {
    title: "DEMO SOURCE: DataFoundry synthetic data product brief",
    url: "/demo-sources/datafoundry-product",
    publisher: "DataFoundry Labs Demo Site",
    publishedAt: "2026-02-06T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "company",
    origin: "mock",
    companyId: "company-datafoundry",
    contactId: "contact-aisha-okafor",
    snippet:
      "The demo product brief describes lineage, policy metadata, and evaluation harnesses for synthetic data.",
    supportsClaims: [
      "DataFoundry Labs focuses on governed synthetic data pipelines for enterprise AI systems.",
      "The product is categorized as data infrastructure in this demo.",
    ],
  },
  {
    title: "DEMO SOURCE: Telemetry Fabric pre-seed note",
    url: "/demo-sources/telemetryfabric-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2026-04-22T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-telemetryfabric",
    contactId: "contact-luis-alvarez",
    snippet:
      "Telemetry Fabric, a fictional demo company, is represented as having raised a $1.1M pre-seed round.",
    supportsClaims: [
      "Telemetry Fabric is represented in the demo dataset as having raised a $1.1M pre-seed round on April 22, 2026.",
      "Luis Alvarez is represented as Telemetry Fabric's co-founder and CTO.",
    ],
  },
  {
    title: "DEMO SOURCE: Telemetry Fabric AgentOps demo",
    url: "/demo-sources/telemetryfabric-product",
    publisher: "Telemetry Fabric Demo Site",
    publishedAt: "2026-05-02T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "company",
    origin: "mock",
    companyId: "company-telemetryfabric",
    contactId: "contact-luis-alvarez",
    snippet:
      "The demo page describes joining traces, prompts, tool calls, and evaluation outcomes for AI agent operations.",
    supportsClaims: [
      "Telemetry Fabric focuses on AI agent observability across traces, prompts, tool calls, and evaluations.",
      "The product is categorized as model observability in this demo.",
    ],
  },
  {
    title: "DEMO SOURCE: EdgePilot seed financing note",
    url: "/demo-sources/edgepilot-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2025-10-02T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-edgepilot",
    contactId: "contact-theo-nguyen",
    snippet:
      "EdgePilot, a fictional demo company, is represented as having raised $2.4M for edge inference runtime tooling.",
    supportsClaims: [
      "EdgePilot is represented in the demo dataset as having raised a $2.4M seed round on October 2, 2025.",
      "Theo Nguyen is represented as EdgePilot's founder and CEO.",
    ],
  },
  {
    title: "DEMO SOURCE: CompileWorks launch memo",
    url: "/demo-sources/compileworks-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2026-03-11T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-compileworks",
    contactId: "contact-elena-petrova",
    snippet:
      "CompileWorks, a fictional demo company, is represented as having raised $2.1M for AI-generated code verification.",
    supportsClaims: [
      "CompileWorks is represented in the demo dataset as having raised a $2.1M seed round on March 11, 2026.",
      "Elena Petrova is represented as CompileWorks' founder.",
    ],
  },
  {
    title: "DEMO SOURCE: Context Harbor Series A note",
    url: "/demo-sources/contextharbor-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2025-08-20T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-contextharbor",
    contactId: "contact-noah-kim",
    snippet:
      "Context Harbor, a fictional demo company, is represented as having raised a $12M Series A round.",
    supportsClaims: [
      "Context Harbor is represented in the demo dataset as having raised a $12M Series A round on August 20, 2025.",
      "The company is outside the preferred seed-stage filter.",
    ],
  },
  {
    title: "DEMO SOURCE: SecureWeights seed financing note",
    url: "/demo-sources/secureweights-seed",
    publisher: "LargeVCModel Demo Wire",
    publishedAt: "2026-05-01T00:00:00.000Z",
    accessedAt: FIXED_ACCESS_DATE,
    sourceType: "funding",
    origin: "mock",
    companyId: "company-secureweights",
    contactId: "contact-hana-sato",
    snippet:
      "SecureWeights, a fictional demo company, is represented as having raised a seed round outside the Bay Area.",
    supportsClaims: [
      "SecureWeights is represented in the demo dataset as having raised a $3.0M seed round on May 1, 2026.",
      "The company is outside the Bay Area geography filter.",
    ],
  },
];

export const portfolioPeople = [
  {
    id: "portfolio-nikhil-shah",
    label: "Nikhil Shah",
    type: "portfolio_founder",
    detail: "CTO at Northstar portfolio company Runloop Systems",
  },
  {
    id: "advisor-lila-fernandez",
    label: "Lila Fernandez",
    type: "advisor",
    detail: "Infrastructure advisor and former distributed systems VP",
  },
  {
    id: "portfolio-nora-patel",
    label: "Nora Patel",
    type: "portfolio_founder",
    detail: "Security founder in the Northstar portfolio",
  },
  {
    id: "advisor-omar-saleh",
    label: "Omar Saleh",
    type: "advisor",
    detail: "Former ML platform lead and angel advisor",
  },
];

export const demoRelationshipEdges = [
  {
    id: "edge-ava-maya",
    fromNodeId: "partner-ava",
    fromNodeLabel: "Ava Sterling",
    fromNodeType: "partner",
    toNodeId: "contact-maya-chen",
    toNodeLabel: "Maya Chen",
    toNodeType: "founder",
    relationship: "Met at AI Systems Summit",
    strength: 7,
    evidence: "Internal CRM note from May 2026 says Ava met Maya after a retrieval operations session.",
    sourceType: "internal_crm",
    sourceId: "internal-crm",
  },
  {
    id: "edge-nikhil-maya",
    fromNodeId: "portfolio-nikhil-shah",
    fromNodeLabel: "Nikhil Shah",
    fromNodeType: "portfolio_founder",
    toNodeId: "contact-maya-chen",
    toNodeLabel: "Maya Chen",
    toNodeType: "founder",
    relationship: "Shared event working session",
    strength: 8,
    evidence: "Demo event attendance source places both in the same retrieval operations session.",
    sourceType: "event_attendance",
    sourceId: "/demo-sources/ai-systems-summit-2026",
  },
  {
    id: "edge-ben-priya",
    fromNodeId: "partner-ben",
    fromNodeLabel: "Ben Ortiz",
    fromNodeType: "partner",
    toNodeId: "contact-priya-raman",
    toNodeLabel: "Priya Raman",
    toNodeType: "founder",
    relationship: "Attended technical talk",
    strength: 7,
    evidence: "Seeded internal note: Ben flagged Priya's GPU scheduling talk as technically credible.",
    sourceType: "internal_crm",
    sourceId: "internal-crm",
  },
  {
    id: "edge-lila-priya",
    fromNodeId: "advisor-lila-fernandez",
    fromNodeLabel: "Lila Fernandez",
    fromNodeType: "advisor",
    toNodeId: "contact-priya-raman",
    toNodeLabel: "Priya Raman",
    toNodeType: "founder",
    relationship: "Prior employer overlap",
    strength: 6,
    evidence: "Manually entered advisor note says both worked in distributed systems groups at different times.",
    sourceType: "manually_entered",
    sourceId: "internal-crm",
  },
  {
    id: "edge-rina-samira",
    fromNodeId: "partner-rina",
    fromNodeLabel: "Rina Kapoor",
    fromNodeType: "partner",
    toNodeId: "contact-samira-haddad",
    toNodeLabel: "Samira Haddad",
    toNodeType: "founder",
    relationship: "Roundtable follow-up",
    strength: 6,
    evidence: "Internal CRM note from enterprise AI governance roundtable.",
    sourceType: "internal_crm",
    sourceId: "internal-crm",
  },
  {
    id: "edge-nora-devon",
    fromNodeId: "portfolio-nora-patel",
    fromNodeLabel: "Nora Patel",
    fromNodeType: "portfolio_founder",
    toNodeId: "contact-devon-brooks",
    toNodeLabel: "Devon Brooks",
    toNodeType: "founder",
    relationship: "Former security community connection",
    strength: 5,
    evidence: "Seeded manually entered CRM relationship from a security operator dinner.",
    sourceType: "manually_entered",
    sourceId: "internal-crm",
  },
  {
    id: "edge-omar-aisha",
    fromNodeId: "advisor-omar-saleh",
    fromNodeLabel: "Omar Saleh",
    fromNodeType: "advisor",
    toNodeId: "contact-aisha-okafor",
    toNodeLabel: "Aisha Okafor",
    toNodeType: "founder",
    relationship: "Shared university lab network",
    strength: 6,
    evidence: "Internal CRM note: shared Berkeley AI lab network.",
    sourceType: "internal_crm",
    sourceId: "internal-crm",
  },
  {
    id: "edge-nikhil-luis",
    fromNodeId: "portfolio-nikhil-shah",
    fromNodeLabel: "Nikhil Shah",
    fromNodeType: "portfolio_founder",
    toNodeId: "contact-luis-alvarez",
    toNodeLabel: "Luis Alvarez",
    toNodeType: "founder",
    relationship: "AgentOps Demo Day attendee",
    strength: 9,
    evidence: "Seeded event relationship from the demo AgentOps session.",
    sourceType: "event_attendance",
    sourceId: "/demo-sources/telemetryfabric-product",
  },
];

export const demoCalendarSlots = [
  {
    id: "slot-ava-1",
    partnerId: "partner-ava",
    startTime: "2026-07-23T16:00:00.000Z",
    endTime: "2026-07-23T16:30:00.000Z",
    timezone: "America/Los_Angeles",
    status: "available",
    label: "Best: thesis partner and warm context",
  },
  {
    id: "slot-ava-2",
    partnerId: "partner-ava",
    startTime: "2026-07-24T18:00:00.000Z",
    endTime: "2026-07-24T18:30:00.000Z",
    timezone: "America/Los_Angeles",
    status: "available",
    label: "Backup slot",
  },
  {
    id: "slot-ben-1",
    partnerId: "partner-ben",
    startTime: "2026-07-23T20:00:00.000Z",
    endTime: "2026-07-23T20:30:00.000Z",
    timezone: "America/Los_Angeles",
    status: "available",
    label: "Technical diligence slot",
  },
  {
    id: "slot-rina-1",
    partnerId: "partner-rina",
    startTime: "2026-07-25T17:00:00.000Z",
    endTime: "2026-07-25T17:30:00.000Z",
    timezone: "America/Los_Angeles",
    status: "available",
    label: "Enterprise AI angle",
  },
];

export const demoSampleReplies = [
  {
    type: "interested",
    body: "Thanks for reaching out. The timing is good after the seed, and I would be happy to compare notes next week.",
  },
  {
    type: "not_interested",
    body: "Appreciate the note, but we are not taking new investor conversations right now.",
  },
  {
    type: "follow_up_later",
    body: "Could you check back in September? We are heads down on launch milestones.",
  },
  {
    type: "introduction_request",
    body: "This looks relevant. Could you send more context and include Nikhil if he is comfortable making the intro?",
  },
  {
    type: "wrong_person",
    body: "I am not the right person for fundraising conversations. Please contact our CEO.",
  },
  {
    type: "ambiguous",
    body: "Interesting. I need to think about whether this makes sense right now.",
  },
];

export const demoSourceArticles: Record<string, { title: string; body: string; notice: string }> = {
  "internal-crm-snapshot": {
    title: "Internal CRM Snapshot - Demo Data",
    notice: "This is seeded fictional private CRM data for the local LargeVCModel demo.",
    body: "The CRM snapshot contains founder identities, relationship strengths, prior interactions, and status history. It is intentionally marked as Internal CRM and should not be treated as public web research.",
  },
  "vectorforge-seed": {
    title: "DEMO SOURCE: VectorForge announces $3.2M seed round",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "VectorForge AI is represented in this demo as a San Francisco company that raised a $3.2M seed round on May 14, 2026. The article names Maya Chen as co-founder and CEO and describes a focus on retrieval infrastructure operations.",
  },
  "vectorforge-product": {
    title: "DEMO SOURCE: VectorForge retrieval reliability product brief",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product brief describes vector index monitoring, retrieval drift detection, and cost-aware index capacity management for teams operating production retrieval systems.",
  },
  "ai-systems-summit-2026": {
    title: "DEMO SOURCE: AI Systems Summit 2026 attendee note",
    notice: "Fictional event record used only for source attribution testing.",
    body: "The demo program records Maya Chen and Nikhil Shah in the same retrieval operations working session. This supports an event-based warm introduction path, not a verified social relationship.",
  },
  "kernelgrid-seed": {
    title: "DEMO SOURCE: KernelGrid seed financing brief",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "KernelGrid is represented as having raised $4.5M on February 18, 2026 to build GPU job scheduling infrastructure. Priya Raman is represented as founder and CTO.",
  },
  "kernelgrid-product": {
    title: "DEMO SOURCE: KernelGrid GPU scheduler product page",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product page describes GPU job scheduling, usage forecasting, and routing across heterogeneous clusters for AI application teams.",
  },
  "modelframe-seed": {
    title: "DEMO SOURCE: ModelFrame seed launch note",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "ModelFrame is represented as having raised $2.7M on June 3, 2026 for LLM regression testing and evaluation infrastructure. Samira Haddad is represented as co-founder and CEO.",
  },
  "modelframe-product": {
    title: "DEMO SOURCE: ModelFrame evaluation pipeline brief",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The brief describes test suites, experiment tracking, release regression monitoring, and failure clustering for production LLM product teams.",
  },
  "guardlayer-seed": {
    title: "DEMO SOURCE: GuardLayer seed funding note",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "GuardLayer is represented as having raised $2.8M on December 9, 2025 to build runtime security for AI agents. Devon Brooks is represented as founder.",
  },
  "guardlayer-product": {
    title: "DEMO SOURCE: GuardLayer agent security product note",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product note describes runtime policy enforcement, permission gates, and action replay for tool-using AI agents.",
  },
  "datafoundry-seed": {
    title: "DEMO SOURCE: DataFoundry seed announcement",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "DataFoundry Labs is represented as having raised $3.7M on January 29, 2026 for governed synthetic data pipelines. Aisha Okafor is represented as co-founder and CEO.",
  },
  "datafoundry-product": {
    title: "DEMO SOURCE: DataFoundry synthetic data product brief",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product brief describes synthetic datasets with lineage, policy metadata, and evaluation harnesses for regulated enterprise AI systems.",
  },
  "telemetryfabric-seed": {
    title: "DEMO SOURCE: Telemetry Fabric pre-seed note",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "Telemetry Fabric is represented as having raised a $1.1M pre-seed round on April 22, 2026. Luis Alvarez is represented as co-founder and CTO.",
  },
  "telemetryfabric-product": {
    title: "DEMO SOURCE: Telemetry Fabric AgentOps demo",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The page describes AI agent observability across traces, prompts, tool calls, and evaluation outcomes for root-cause analysis.",
  },
  "edgepilot-seed": {
    title: "DEMO SOURCE: EdgePilot seed financing note",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "EdgePilot is represented as having raised $2.4M on October 2, 2025 for edge inference runtime tooling. Theo Nguyen is represented as founder and CEO.",
  },
  "edgepilot-product": {
    title: "DEMO SOURCE: EdgePilot product brief",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product brief describes compact inference runtimes for edge devices in retail, logistics, and field service settings.",
  },
  "compileworks-seed": {
    title: "DEMO SOURCE: CompileWorks launch memo",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "CompileWorks is represented as having raised $2.1M on March 11, 2026 to build compiler diagnostics and deployment verification for AI-generated code. Elena Petrova is represented as founder.",
  },
  "compileworks-product": {
    title: "DEMO SOURCE: CompileWorks product note",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product note describes AI-generated code diagnostics, deployment verification, and build-time failure analysis.",
  },
  "contextharbor-seed": {
    title: "DEMO SOURCE: Context Harbor Series A note",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "Context Harbor is represented as having raised a $12M Series A round on August 20, 2025, which is outside the preferred seed-stage filter for this demo scenario.",
  },
  "contextharbor-product": {
    title: "DEMO SOURCE: Context Harbor product note",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product note describes enterprise knowledge retrieval governance for regulated customer-support teams.",
  },
  "secureweights-seed": {
    title: "DEMO SOURCE: SecureWeights seed financing note",
    notice: "Fictional public-source artifact used only for source attribution testing.",
    body: "SecureWeights is represented as having raised a $3.0M seed round on May 1, 2026. The company is based in Seattle, outside the Bay Area geography filter.",
  },
  "secureweights-product": {
    title: "DEMO SOURCE: SecureWeights product note",
    notice: "Fictional product page used only for source attribution testing.",
    body: "The product note describes model provenance, checksum policies, and regulated deployment approval workflows.",
  },
};
